import product2 from "@/assets/product-2.jpg";
import product3 from "@/assets/product-3.jpg";
import product4 from "@/assets/product-4.jpg";
import type { Product, Designer } from "@/types";

export const DEMO_CREDENTIALS = [
  { role: "customer", email: "customer@betees.com", password: "demo123", name: "Priya Sharma" },
  { role: "designer", email: "designer@betees.com", password: "demo123", name: "Arjun Kapoor" },
  { role: "tailor", email: "tailor@betees.com", password: "demo123", name: "Suresh Nair" },
  { role: "brand", email: "brand@betees.com", password: "demo123", name: "Vikram Mehta" },
  { role: "creator", email: "creator@betees.com", password: "demo123", name: "Neha Gupta" },
  { role: "admin", email: "admin@betees.com", password: "demo123", name: "Admin User" },
];

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Imperial Burgundy Cashmere Trench",
    brand: "Aurelia Couture",
    price: 78500,
    originalPrice: 95000,
    category: "Outerwear",
    image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&h=800&fit=crop&q=80&auto=format",
    aiMatch: 96,
    fabric: "100% Mongolian Cashmere",
    description: "Architectural double-breasted design with hand-rolled lapels, crafted from the finest Mongolian cashmere.",
    rating: 4.9,
    reviews: 42,
    inStock: true,
    sizes: ["XS", "S", "M", "L", "XL", "Custom"],
    tags: ["trending", "ai-pick", "new"],
  },
  {
    id: "2",
    name: "Structured Wool-Silk Tuxedo Blazer",
    brand: "Atelier Vesper",
    price: 52000,
    category: "Blazers",
    image: product2,
    aiMatch: 98,
    fabric: "Biella Super 160s Wool",
    description: "Masterfully constructed with floating horsehair canvas chest piece, burgundy silk peak lapels.",
    rating: 4.95,
    reviews: 38,
    inStock: true,
    sizes: ["38R", "40R", "42R", "44R", "Custom"],
    tags: ["bestseller", "ai-pick"],
  },
  {
    id: "3",
    name: "Silk Zardozi Embroidered Lehenga",
    brand: "House of Rohit Bal",
    price: 145000,
    originalPrice: 180000,
    category: "Ethnic Wear",
    image: product3,
    aiMatch: 91,
    fabric: "Pure Silk with Zardozi",
    description: "Exquisite bridal lehenga with intricate zardozi embroidery in rose gold and ivory.",
    rating: 4.8,
    reviews: 27,
    inStock: true,
    sizes: ["XS", "S", "M", "L", "Custom"],
    tags: ["bridal", "ethnic"],
  },
  {
    id: "4",
    name: "Obsidian Drape Cape Dress",
    brand: "Maison Noir",
    price: 38900,
    category: "Dresses",
    image: product4,
    aiMatch: 94,
    fabric: "Pure Merino Wool",
    description: "Asymmetric architectural drape with sculptural shoulder line, single-seam obsidian double crepe.",
    rating: 4.85,
    reviews: 31,
    inStock: true,
    sizes: ["XS", "S", "M", "L"],
    tags: ["limited", "editorial"],
  },
  {
    id: "5",
    name: "Fluid Silk Palazzo Trousers",
    brand: "Studio Cadence",
    price: 24500,
    category: "Trousers",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4b4e83?w=600&h=800&fit=crop&q=80",
    aiMatch: 95,
    fabric: "Heavy Habotai Silk",
    description: "High-waisted fluid silk palazzo with invisible zip, pre-hemmed to your measurements.",
    rating: 4.7,
    reviews: 55,
    inStock: true,
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["trending"],
  },
  {
    id: "6",
    name: "Bandhgala Bundi Jacket",
    brand: "Tarun Tahiliani",
    price: 35000,
    category: "Ethnic Men",
    image: "https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600&h=800&fit=crop&q=80",
    aiMatch: 89,
    fabric: "Tussar Silk",
    description: "Contemporary take on the traditional Bandhgala with geometric pintuck detailing.",
    rating: 4.75,
    reviews: 22,
    inStock: true,
    sizes: ["S", "M", "L", "XL", "Custom"],
    tags: ["ethnic", "men"],
  },
  {
    id: "7",
    name: "Raw Edge Riviera Linen Suit",
    brand: "Atelier Vesper",
    price: 44000,
    category: "Suits",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=800&fit=crop&q=80",
    aiMatch: 93,
    fabric: "Organic Belgian Linen",
    description: "Unlined ivory linen safari tailoring for summer, horn button closures.",
    rating: 4.8,
    reviews: 19,
    inStock: true,
    sizes: ["S", "M", "L", "XL"],
    tags: ["summer", "men"],
  },
  {
    id: "8",
    name: "Sculpted Rose Silk Halter Blouse",
    brand: "Aurelia Couture",
    price: 18500,
    category: "Tops",
    image: "https://images.unsplash.com/photo-1575886876069-f50e42e55c75?w=600&h=800&fit=crop&q=80",
    aiMatch: 97,
    fabric: "Mulberry Silk Charmeuse",
    description: "Bias-cut heavy mulberry silk charmeuse with drape open spine construction.",
    rating: 4.9,
    reviews: 44,
    inStock: true,
    sizes: ["XS", "S", "M", "L"],
    tags: ["ai-pick", "trending"],
  },
];

export const DESIGNERS: Designer[] = [
  {
    id: "1",
    name: "Matteo Moretti",
    studio: "Sartoria Vespera",
    location: "Milan, Italy",
    specialty: "Milanese Hand-Canvassed Tailoring",
    rating: 4.98,
    reviews: 142,
    experience: "28 Years",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&q=80",
    verified: true,
  },
  {
    id: "2",
    name: "Alistair Finch",
    studio: "Cadence & Holme",
    location: "Savile Row, London",
    specialty: "Military Architecture & Roped Shoulders",
    rating: 4.96,
    reviews: 189,
    experience: "34 Years",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&q=80",
    verified: true,
  },
  {
    id: "3",
    name: "Priya Nair",
    studio: "Atelier Priya",
    location: "Mumbai, India",
    specialty: "Contemporary Indian Couture & Bridal",
    rating: 4.95,
    reviews: 98,
    experience: "18 Years",
    image: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop&q=80",
    verified: true,
  },
  {
    id: "4",
    name: "Ravi Bhandari",
    studio: "Bhandari Couture",
    location: "Jaipur, India",
    specialty: "Handcraft Embroidery & Bridal Trousseau",
    rating: 4.92,
    reviews: 76,
    experience: "22 Years",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&q=80",
    verified: true,
  },
  {
    id: "5",
    name: "Genevieve Delacroix",
    studio: "Atelier Genevieve",
    location: "Paris, France",
    specialty: "Parisian Haute Couture Draping",
    rating: 4.99,
    reviews: 112,
    experience: "26 Years",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&q=80",
    verified: true,
  },
  {
    id: "6",
    name: "Kavya Menon",
    studio: "Studio Kavya",
    location: "Bengaluru, India",
    specialty: "Modern Fusion & Sustainable Fashion",
    rating: 4.88,
    reviews: 65,
    experience: "12 Years",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&q=80",
    verified: true,
  },
];

export const CATEGORIES = [
  { id: "men", name: "Men", count: 342, image: "https://images.unsplash.com/photo-1617137968427-85924c800a22?w=400&h=500&fit=crop&q=80" },
  { id: "women", name: "Women", count: 586, image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&h=500&fit=crop&q=80" },
  { id: "ethnic", name: "Ethnic", count: 215, image: "https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=400&h=500&fit=crop&q=80" },
  { id: "accessories", name: "Accessories", count: 198, image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=500&fit=crop&q=80" },
  { id: "footwear", name: "Footwear", count: 124, image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=500&fit=crop&q=80" },
];

export const AI_STYLE_RESPONSES: Record<string, string> = {
  wedding: '"For a grand Indian wedding, we recommend pairing an ivory silk lehenga with intricate zardozi embroidery, complemented by a structured blouse in burgundy and rose gold accents. Your warm undertone enhances these regal tones perfectly."',
  office: '"For a creative director capsule wardrobe, curate clean single-button charcoal blazers paired with raw-silk loose shirting and wide pleated trousers — commanding presence with fluid movement."',
  casual: '"Your weekend style profile calls for relaxed Belgian linen in warm ivory, tailored slim-fit chinos in stone, and handcrafted leather kolhapuris. Effortlessly elevated casual."',
  party: '"An avant-garde party look for you: sculpted rose gold silk halter paired with fluid palazzo trousers in midnight charcoal. The color contrast is algorithmically calibrated to your skin tone."',
  festive: '"Festive dressing curated for you: a rich tussar silk bandhgala with hand-block prints in burgundy and gold, perfect for Diwali celebrations — exuding cultural richness with modern cuts."',
};

export const TESTIMONIALS = [
  {
    id: "1",
    name: "Riya Malhotra",
    location: "Mumbai",
    avatar: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=80&h=80&fit=crop",
    text: "The AI Stylist understood my body type and occasion perfectly. My wedding trousseau was curated in minutes, and every piece fit like it was made for me — because it was!",
    rating: 5,
    product: "Custom Bridal Lehenga",
  },
  {
    id: "2",
    name: "Aryan Kapoor",
    location: "Delhi",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop",
    text: "Ordered a bespoke tuxedo for my sister's wedding. The virtual fitting was spot on — zero alterations needed. The Biella wool quality is unmatched at this price point.",
    rating: 5,
    product: "Bespoke Tuxedo",
  },
  {
    id: "3",
    name: "Sneha Patel",
    location: "Ahmedabad",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&h=80&fit=crop",
    text: "As a fashion creator, Betees has transformed how I build my looks. The Digital Wardrobe feature helps me plan weeks of content in advance. Absolutely game-changing.",
    rating: 5,
    product: "Creator Platform",
  },
];

export const COMMUNITY_POSTS = [
  {
    id: "1",
    user: "Mihir Shah",
    handle: "@mihir.style",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=60&h=60&fit=crop",
    image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&h=500&fit=crop",
    caption: "My Betees AI curated this look for my Tokyo trip. The cashmere camel coat + wide trousers combo is perfection. 🔥",
    likes: 342,
    comments: 28,
    saves: 91,
    tags: ["#BeteesStyle", "#AIFashion"],
  },
  {
    id: "2",
    user: "Ananya Roy",
    handle: "@ananya.couture",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=60&h=60&fit=crop",
    image: product3,
    caption: "My custom bridal lehenga from House of Rohit Bal via Betees. The AI matched my skin tone to this exact color palette — I cried when I first wore it. ✨",
    likes: 1247,
    comments: 156,
    saves: 388,
    tags: ["#BeteesWedding", "#Bridal"],
  },
  {
    id: "3",
    user: "Karan Mehta",
    handle: "@karan.elegance",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=60&h=60&fit=crop",
    image: product2,
    caption: "Atelier Vesper tuxedo blazer arrived today. The Milanese lapel stitching is extraordinary. Zero alterations needed — Betees AI fit prediction is incredibly accurate.",
    likes: 521,
    comments: 47,
    saves: 134,
    tags: ["#BespokeFashion", "#BeteesStyle"],
  },
  {
    id: "4",
    user: "Ishita Verma",
    handle: "@ishita.fashion",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=60&h=60&fit=crop",
    image: product4,
    caption: "The Obsidian Drape Cape from Maison Noir. Wore this to a gallery opening and received 50+ compliments. Betees knows my aesthetic better than I do! 🖤",
    likes: 789,
    comments: 63,
    saves: 212,
    tags: ["#EditorialFashion", "#BeteesStyle"],
  },
];

export const NAVBAR_LINKS = [
  { label: "Home", path: "/" },
  { label: "Discover", path: "/discover" },
  { label: "Shop", path: "/shop" },
  { label: "Designers", path: "/designers" },
  { label: "Tailors", path: "/tailors" },
  { label: "Creators", path: "/creators" },
  { label: "Trends", path: "/trends" },
  { label: "Community", path: "/community" },
  { label: "AI Stylist", path: "/ai-stylist" },
];

export const QUICK_STYLE_CHIPS = [
  { label: "Wedding Look", icon: "💍", query: "wedding" },
  { label: "Office Style", icon: "💼", query: "office" },
  { label: "Casual Chic", icon: "☀️", query: "casual" },
  { label: "Party Ready", icon: "🎉", query: "party" },
  { label: "Festive Season", icon: "✨", query: "festive" },
];

export const formatINR = (amount: number): string => {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};
